<script setup lang="ts">
// both components' declaration file are generated by vue-tsx
import Button from '../es/components/button/Button';
import Alert from '../es/components/alert/Alert';
</script>

<template>
  <div>
    <!-- written in tsx and props autocomplete works well  -->
    <Alert></Alert>

    <!-- written in vue sfc and props autocomplete does not work -->
    <Button></Button>
  </div>
</template>
